# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import arrwdb_pb2 as arrwdb__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arrwdb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArrwDBStub(object):
    """Core vector database operations via gRPC.
    Lower latency than REST for high-throughput search workloads.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/arrwdb.ArrwDB/Search',
                request_serializer=arrwdb__pb2.SearchRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SearchByText = channel.unary_unary(
                '/arrwdb.ArrwDB/SearchByText',
                request_serializer=arrwdb__pb2.TextSearchRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.AddDocument = channel.unary_unary(
                '/arrwdb.ArrwDB/AddDocument',
                request_serializer=arrwdb__pb2.AddDocumentRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.AddDocumentResponse.FromString,
                _registered_method=True)
        self.AddDocumentWithEmbeddings = channel.unary_unary(
                '/arrwdb.ArrwDB/AddDocumentWithEmbeddings',
                request_serializer=arrwdb__pb2.AddDocumentWithEmbeddingsRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.AddDocumentResponse.FromString,
                _registered_method=True)
        self.UpsertVector = channel.unary_unary(
                '/arrwdb.ArrwDB/UpsertVector',
                request_serializer=arrwdb__pb2.UpsertVectorRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.UpsertVectorResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/arrwdb.ArrwDB/DeleteDocument',
                request_serializer=arrwdb__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/arrwdb.ArrwDB/HybridSearch',
                request_serializer=arrwdb__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arrwdb.ArrwDB/HealthCheck',
                request_serializer=arrwdb__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=arrwdb__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ArrwDBServicer(object):
    """Core vector database operations via gRPC.
    Lower latency than REST for high-throughput search workloads.

    """

    def Search(self, request, context):
        """Search for nearest neighbors by vector embedding.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByText(self, request, context):
        """Search by text query (generates embedding server-side).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDocument(self, request, context):
        """Add a document with text (auto-embeds).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDocumentWithEmbeddings(self, request, context):
        """Add a document with pre-computed embeddings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertVector(self, request, context):
        """Upsert a vector by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Delete a document.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Hybrid search (vector + keyword via RRF).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArrwDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=arrwdb__pb2.SearchRequest.FromString,
                    response_serializer=arrwdb__pb2.SearchResponse.SerializeToString,
            ),
            'SearchByText': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByText,
                    request_deserializer=arrwdb__pb2.TextSearchRequest.FromString,
                    response_serializer=arrwdb__pb2.SearchResponse.SerializeToString,
            ),
            'AddDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocument,
                    request_deserializer=arrwdb__pb2.AddDocumentRequest.FromString,
                    response_serializer=arrwdb__pb2.AddDocumentResponse.SerializeToString,
            ),
            'AddDocumentWithEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocumentWithEmbeddings,
                    request_deserializer=arrwdb__pb2.AddDocumentWithEmbeddingsRequest.FromString,
                    response_serializer=arrwdb__pb2.AddDocumentResponse.SerializeToString,
            ),
            'UpsertVector': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertVector,
                    request_deserializer=arrwdb__pb2.UpsertVectorRequest.FromString,
                    response_serializer=arrwdb__pb2.UpsertVectorResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=arrwdb__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=arrwdb__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=arrwdb__pb2.HybridSearchRequest.FromString,
                    response_serializer=arrwdb__pb2.SearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=arrwdb__pb2.HealthCheckRequest.FromString,
                    response_serializer=arrwdb__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arrwdb.ArrwDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arrwdb.ArrwDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArrwDB(object):
    """Core vector database operations via gRPC.
    Lower latency than REST for high-throughput search workloads.

    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/Search',
            arrwdb__pb2.SearchRequest.SerializeToString,
            arrwdb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/SearchByText',
            arrwdb__pb2.TextSearchRequest.SerializeToString,
            arrwdb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/AddDocument',
            arrwdb__pb2.AddDocumentRequest.SerializeToString,
            arrwdb__pb2.AddDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDocumentWithEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/AddDocumentWithEmbeddings',
            arrwdb__pb2.AddDocumentWithEmbeddingsRequest.SerializeToString,
            arrwdb__pb2.AddDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/UpsertVector',
            arrwdb__pb2.UpsertVectorRequest.SerializeToString,
            arrwdb__pb2.UpsertVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/DeleteDocument',
            arrwdb__pb2.DeleteDocumentRequest.SerializeToString,
            arrwdb__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/HybridSearch',
            arrwdb__pb2.HybridSearchRequest.SerializeToString,
            arrwdb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrwdb.ArrwDB/HealthCheck',
            arrwdb__pb2.HealthCheckRequest.SerializeToString,
            arrwdb__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
