{{- if and .Values.arrwdb.auth.enabled (not .Values.arrwdb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arrwdb.fullname" . }}-auth
  labels:
    {{- include "arrwdb.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.arrwdb.auth.existingSecretKey }}: {{ .Values.arrwdb.auth.apiKey | b64enc | quote }}
{{- end }}
